# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Quick host-based tests (fast feedback)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (host)
        run: pytest -q

      # Build Docker image with modern BuildKit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-fitness-app:ci .

      # Run tests inside container
      - name: Run pytest inside Docker
        run: docker run --rm my-fitness-app:ci pytest -q
